on:
  push:
    branches:
      - master
    paths:
      - "**.js"
      - "**.ts"
      - "**.cjs"
      - "examples/**"
      - "package.json"
      - "package-lock.json"
      - ".gitignore"
      - ".github/workflows/**"
      - "!dist/**"
    tags:
      - "v*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
